GET http://localhost:3000/languages

###

GET http://localhost:3000/languages/2

###

POST http://localhost:3000/languages
Content-Type: application/json

{
   "name": "Español"
}

###

DELETE http://localhost:3000/languages/2